import React,{useCallback,useEffect,useMemo,useState}from'react';
import*as Reactor from'@datalayer/reactor';
import{bootstrapExtensions,buildReactorFromPlugins,defineContributionPoint,setReactorSharedModules,type LazyPluginRef,type ReactorExtension}from'@datalayer/reactor';
import*as ReactorReact from'@datalayer/reactor/react';
import{useBackendPluginStream,useContributions,usePluginManifests,useReactor}from'@datalayer/reactor/react';
import{Blocks,FileText,Globe2,LoaderCircle,Moon,Palette,Plus,Puzzle,Shield,Sun,Users}from'lucide-react';
import{Alert,Badge,Button,Card,CardContent,CardDescription,CardHeader,CardTitle,Input,Select,Textarea}from'./ui';
import'../styles.css';

type Site={id:string;name:string;slug:string;role:string;theme_slug:string};
type Entry={id:string;title:string;slug:string;body:string;status:string};
type Theme={id:string;name:string;slug:string;description:string};
type Member={id:string;email:string;name:string;disabled:number;role:string};
type Item={label?:string;slug?:string;id?:string};
type Tab='Content'|'Users'|'Sites'|'Themes'|'Extensions';
const ContentTypes=defineContributionPoint<Item>('cmsAstro.contentType');
const ExtensionThemes=defineContributionPoint<Item>('cmsAstro.theme');
const EditorActions=defineContributionPoint<Item>('cmsAstro.editorAction');
const DashboardWidgets=defineContributionPoint<Item>('cmsAstro.dashboardWidget');
const UI={Alert,Badge,Button,Card,CardContent,CardDescription,CardHeader,CardTitle,Input,Select,Textarea};
setReactorSharedModules({react:React,'@datalayer/reactor':Reactor,'@datalayer/reactor/react':ReactorReact,'@cms-astro/ui':UI});

async function api<T>(url:string,init:RequestInit={}):Promise<T>{const response=await fetch(url,init);if(!response.ok)throw new Error((await response.text())||`HTTP ${response.status}`);return response.json()as Promise<T>}

function Shell({apiUrl,remotes}:{apiUrl:string;remotes:(LazyPluginRef|ReactorExtension)[]}){
 const reactor=useMemo(()=>buildReactorFromPlugins(remotes),[remotes]);useReactor(reactor);useBackendPluginStream(apiUrl);
 const[tab,setTab]=useState<Tab>('Content'),[dark,setDark]=useState(false),[busy,setBusy]=useState(true);
 const[sites,setSites]=useState<Site[]>([]),[siteId,setSiteId]=useState('site-main'),[entries,setEntries]=useState<Entry[]>([]),[themes,setThemes]=useState<Theme[]>([]),[members,setMembers]=useState<Member[]>([]);
 const[title,setTitle]=useState(''),[body,setBody]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('author'),[notice,setNotice]=useState<string>(),[error,setError]=useState<string>();
 const headers=useMemo(()=>({'content-type':'application/json','X-CMS-User':'u-admin'}),[]);
 const load=useCallback(async()=>{setBusy(true);setError(undefined);try{const[s,e,t,u]=await Promise.all([api<Site[]>(`${apiUrl}/api/cms/sites`,{headers}),api<Entry[]>(`${apiUrl}/api/cms/sites/${siteId}/entries`,{headers}),api<Theme[]>(`${apiUrl}/api/cms/themes`,{headers}),api<Member[]>(`${apiUrl}/api/cms/sites/${siteId}/users`,{headers})]);setSites(s);setEntries(e);setThemes(t);setMembers(u)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}},[apiUrl,headers,siteId]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{document.documentElement.classList.toggle('dark',dark)},[dark]);
 async function createDraft(event:React.SyntheticEvent<HTMLFormElement>){event.preventDefault();try{await api(`${apiUrl}/api/cms/sites/${siteId}/entries`,{method:'POST',headers,body:JSON.stringify({collection:'posts',title,body})});setTitle('');setBody('');setNotice('Draft created.');await load()}catch(reason){setError(String(reason))}}
 async function publish(entry:Entry){try{await api(`${apiUrl}/api/cms/sites/${siteId}/entries/${entry.id}/publish`,{method:'POST',headers});setNotice(`Published “${entry.title}”.`);await load()}catch(reason){setError(String(reason))}}
 async function addUser(event:React.SyntheticEvent<HTMLFormElement>){event.preventDefault();try{const user=await api<Member>(`${apiUrl}/api/cms/sites/${siteId}/users`,{method:'POST',headers,body:JSON.stringify({name,email})});await api(`${apiUrl}/api/cms/sites/${siteId}/memberships`,{method:'PUT',headers,body:JSON.stringify({user_id:user.id,role})});setName('');setEmail('');setNotice(`Added ${user.name}.`);await load()}catch(reason){setError(String(reason))}}
 async function changeRole(userId:string,next:string){try{await api(`${apiUrl}/api/cms/sites/${siteId}/memberships`,{method:'PUT',headers,body:JSON.stringify({user_id:userId,role:next})});await load()}catch(reason){setError(String(reason))}}
 async function toggleUser(user:Member){try{await api(`${apiUrl}/api/cms/sites/${siteId}/users/${user.id}`,{method:'PATCH',headers,body:JSON.stringify({disabled:!user.disabled})});await load()}catch(reason){setError(String(reason))}}
 async function activateTheme(theme:Theme){try{await api(`${apiUrl}/api/cms/sites/${siteId}/theme`,{method:'PATCH',headers,body:JSON.stringify({theme:theme.slug})});setNotice(`Activated ${theme.name}.`);await load()}catch(reason){setError(String(reason))}}
 const plugins=usePluginManifests(),contentTypes=useContributions(ContentTypes),extensionThemes=useContributions(ExtensionThemes),actions=useContributions(EditorActions),widgets=useContributions(DashboardWidgets),activeSite=sites.find(site=>site.id===siteId);
 const nav:[Tab,React.ElementType][]=[['Content',FileText],['Users',Users],['Sites',Globe2],['Themes',Palette],['Extensions',Puzzle]];
 return <div className="min-h-screen bg-background text-foreground"><header className="flex items-center justify-between border-b px-5 py-3"><div><h1 className="font-semibold">Reactor CMS</h1><p className="text-xs text-muted-foreground">Astro live content administration</p></div><Button size="icon" variant="ghost" aria-label="Toggle theme" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={16}/>:<Moon size={16}/>}</Button></header><div className="mx-auto grid max-w-7xl md:grid-cols-[210px_minmax(0,1fr)]"><nav className="flex gap-1 overflow-auto border-b p-3 md:grid md:content-start md:border-b-0 md:border-r">{nav.map(([item,Icon])=><Button key={item} variant={tab===item?'default':'ghost'} className="justify-start" onClick={()=>setTab(item)}><Icon size={15}/>{item}</Button>)}</nav><main className="grid content-start gap-4 p-4 md:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">{tab}</h2><p className="text-sm text-muted-foreground">{activeSite?.name??'Loading…'}</p></div><Select value={siteId} onChange={e=>setSiteId(e.target.value)}>{sites.map(site=><option key={site.id} value={site.id}>{site.name} · {site.role}</option>)}</Select></div>{error&&<Alert destructive>{error}</Alert>}{notice&&<Alert>{notice}</Alert>}{busy&&<LoaderCircle className="animate-spin text-primary"/>}
 {tab==='Content'&&<div className="grid items-start gap-4 lg:grid-cols-[2fr_1fr]"><Card><CardHeader><CardTitle>Entries</CardTitle><CardDescription>{entries.length} database-backed items</CardDescription></CardHeader><CardContent className="grid gap-2">{entries.map(entry=><div key={entry.id} className="flex items-center justify-between gap-3 border-b py-2"><div><p className="text-sm font-medium">{entry.title}</p><Badge variant={entry.status==='published'?'success':'muted'}>{entry.status}</Badge> <span className="text-xs text-muted-foreground">/{entry.slug}</span></div>{entry.status!=='published'&&<Button size="sm" onClick={()=>void publish(entry)}>Publish</Button>}</div>)}</CardContent></Card><div className="grid gap-4"><Card><CardHeader><CardTitle>Quick draft</CardTitle><CardDescription>Create a post, then publish it</CardDescription></CardHeader><CardContent><form className="grid gap-2" onSubmit={createDraft}><Input placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)} required/><Textarea rows={8} placeholder="Markdown content" value={body} onChange={e=>setBody(e.target.value)}/><Button type="submit"><Plus size={14}/>Create draft</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Content types</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{contentTypes.map(item=><Badge key={item.id} variant="default">{item.value.label??item.value.slug}</Badge>)}</CardContent></Card></div></div>}
 {tab==='Users'&&<div className="grid items-start gap-4 lg:grid-cols-[2fr_1fr]"><Card><CardHeader><CardTitle>People and access</CardTitle><CardDescription>Roles are scoped to {activeSite?.name}</CardDescription></CardHeader><CardContent className="grid gap-2">{members.map(user=><div key={user.id} className="grid items-center gap-2 border-b py-3 sm:grid-cols-[1fr_140px_auto]"><div><p className="text-sm font-medium">{user.name} {user.disabled?<Badge variant="destructive">disabled</Badge>:null}</p><p className="text-xs text-muted-foreground">{user.email}</p></div><Select value={user.role} onChange={e=>void changeRole(user.id,e.target.value)}><option>viewer</option><option>author</option><option>editor</option><option>admin</option></Select><Button size="sm" variant="outline" onClick={()=>void toggleUser(user)}>{user.disabled?'Enable':'Disable'}</Button></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Add user</CardTitle><CardDescription>Create an account and membership</CardDescription></CardHeader><CardContent><form className="grid gap-2" onSubmit={addUser}><Input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)} required/><Input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><Select value={role} onChange={e=>setRole(e.target.value)}><option>viewer</option><option>author</option><option>editor</option><option>admin</option></Select><Button type="submit"><Plus size={14}/>Add user</Button></form></CardContent></Card></div>}
 {tab==='Sites'&&<div className="grid gap-4 sm:grid-cols-2">{sites.map(site=><Card key={site.id}><CardHeader><CardTitle>{site.name}</CardTitle><CardDescription>/{site.slug}</CardDescription></CardHeader><CardContent><Badge>{site.role}</Badge> <span className="text-xs text-muted-foreground">Theme: {site.theme_slug}</span></CardContent></Card>)}</div>}
 {tab==='Themes'&&<div className="grid gap-4 sm:grid-cols-2">{themes.map(theme=><Card key={theme.id}><CardHeader><CardTitle>{theme.name}</CardTitle><CardDescription>{theme.description}</CardDescription></CardHeader><CardContent><Button disabled={activeSite?.theme_slug===theme.slug} onClick={()=>void activateTheme(theme)}>{activeSite?.theme_slug===theme.slug?'Active':'Activate'}</Button></CardContent></Card>)}{extensionThemes.filter(item=>!themes.some(theme=>theme.slug===item.value.slug)).map(item=><Card key={item.id}><CardHeader><CardTitle>{item.value.label??item.value.slug}</CardTitle><CardDescription>Contributed by {item.plugin}</CardDescription></CardHeader></Card>)}</div>}
 {tab==='Extensions'&&<div className="grid gap-4"><div className="grid gap-3 sm:grid-cols-3">{[['Plugins',plugins.length,Blocks],['Actions',actions.length,Shield],['Widgets',widgets.length,Puzzle]].map(([label,count,Icon])=><Card key={String(label)}><CardContent className="flex items-center justify-between pt-4"><div><p className="text-xs text-muted-foreground">{String(label)}</p><p className="text-2xl font-semibold">{String(count)}</p></div>{React.createElement(Icon as React.ElementType,{size:20,className:'text-primary'})}</CardContent></Card>)}</div>{plugins.map(plugin=><Card key={plugin.name}><CardHeader><CardTitle>{plugin.emoji??'🧩'} {plugin.displayName}</CardTitle><CardDescription>{plugin.description}</CardDescription></CardHeader><CardContent><Badge variant={plugin.activated?'success':'muted'}>{plugin.activated?'active':'available'}</Badge> <code className="text-xs text-muted-foreground">{plugin.name} · {plugin.extension??'host'}</code></CardContent></Card>)}</div>}</main></div></div>
}
export default function AdminApp({apiUrl='http://localhost:8791'}:{apiUrl?:string}){const[remotes,setRemotes]=useState<(LazyPluginRef|ReactorExtension)[]>(),[error,setError]=useState<string>();useEffect(()=>{bootstrapExtensions(apiUrl).then(setRemotes).catch(reason=>setError(String(reason)))},[apiUrl]);return error?<div className="p-6"><Alert destructive>{error}</Alert></div>:remotes?<Shell apiUrl={apiUrl} remotes={remotes}/>:<div className="p-6"><LoaderCircle className="animate-spin"/></div>}
