import React from 'react';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
export const cn=(...inputs:ClassValue[])=>twMerge(clsx(inputs));
export function Button({className,variant='default',size='default',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'default'|'outline'|'ghost'|'destructive';size?:'default'|'sm'|'icon'}){return <button className={cn('inline-flex items-center justify-center gap-2 rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary disabled:pointer-events-none disabled:opacity-50',variant==='default'&&'bg-primary text-primary-foreground hover:opacity-90',variant==='outline'&&'border bg-card hover:bg-accent',variant==='ghost'&&'hover:bg-accent',variant==='destructive'&&'bg-destructive text-white',size==='default'&&'h-9 px-4 text-sm',size==='sm'&&'h-8 px-3 text-xs',size==='icon'&&'h-9 w-9',className)} {...props}/>}
export function Card({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn('rounded-xl border bg-card shadow-sm',className)} {...props}/>}
export function CardHeader({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn('grid gap-1 p-4 pb-2',className)} {...props}/>}
export function CardTitle({className,...props}:React.HTMLAttributes<HTMLHeadingElement>){return <h3 className={cn('text-sm font-semibold',className)} {...props}/>}
export function CardDescription({className,...props}:React.HTMLAttributes<HTMLParagraphElement>){return <p className={cn('text-xs text-muted-foreground',className)} {...props}/>}
export function CardContent({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn('p-4 pt-2',className)} {...props}/>}
export function Badge({className,variant='muted',...props}:React.HTMLAttributes<HTMLSpanElement>&{variant?:'muted'|'default'|'success'|'destructive'}){return <span className={cn('inline-flex rounded-full px-2 py-0.5 text-[11px] font-medium',variant==='muted'&&'bg-muted text-muted-foreground',variant==='default'&&'bg-primary/10 text-primary',variant==='success'&&'bg-success/15 text-success',variant==='destructive'&&'bg-destructive/15 text-destructive',className)} {...props}/>}
export function Input({className,...props}:React.InputHTMLAttributes<HTMLInputElement>){return <input className={cn('h-9 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary',className)} {...props}/>}
export function Textarea({className,...props}:React.TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea className={cn('w-full rounded-md border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-primary',className)} {...props}/>}
export function Select({className,...props}:React.SelectHTMLAttributes<HTMLSelectElement>){return <select className={cn('h-9 rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary',className)} {...props}/>}
export function Alert({children,destructive=false}:{children:React.ReactNode;destructive?:boolean}){return <div className={cn('rounded-md border p-3 text-sm',destructive?'border-destructive/40 bg-destructive/10 text-destructive':'border-primary/30 bg-primary/5 text-primary')}>{children}</div>}
